### PR TITLE
Feature/no sugar tonight in my coffee

### LINKED ISSUE #584: Rcpp no longer builds with RCPP_NO_SUGAR defined
This is mostly due to the fact that `RNGScope` is defined inside `inst/include/Rcpp/stats/random/random.h` and is used outside the stats directory.  There is also a small issue with the `Matrix op scalar` functions in `inst/include/Rcpp/vector/Matrix.h`.

Moving the definition of `RNGScope` outside of stats (to its own file) and including it unconditionally will fix the former.  Protecting the `Matrix op scalar` functions with `#ifndef RCPP_NO_SUGAR` will fix the latter.

### PR DESCRIPTION
**Pull request by dcdillon**
Fixes #584 by the method detailed in the issue report.

### CODE REVIEW

**Comment by thirdwing** [comment]
I think we can merge and it will be better if @dcdillon can add some change log.

**Comment by dcdillon** [comment]
Modified `inst/NEWS.Rd`.  Hope that's what you meant.

**Comment by eddelbuettel** [comment]
Pretty much every repo has a file [ChangeLog](https://github.com/RcppCore/Rcpp/blob/master/ChangeLog). Thought you'd noticed ;-)

**Comment by dcdillon** [comment]
Must be blind.  I looked!  Fixing.

**Comment by dcdillon** [comment]
Would it be reasonable to add a 'no_sugar' plugin so this can be turned on easily on a per-source file basis?

**Comment by eddelbuettel** [comment]
Maybe.  I don't think I'd have use for it.  Why would you turn sugar off, and why can't a `#define` before `#include <Rcpp.h>` do it?

**Comment by dcdillon** [comment]
Just looks cleaner than arbitrarily sticking `#define` in your `.cpp` files.  Not a huge issue, just a thought.

I turn sugar off to get better handling of matrix operations without causing ambiguities in operator calls.

**Pull request merged**
