### PR TITLE
Fixed signed comparison in IndexHash; unit tests for unique()

### PR DESCRIPTION
**Pull request by nathan-russell**
This addresses the compiler warning described in #574, which is also present in `SelfHash`. Unit tests for the sugar function `unique` are also added.

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Sweet.  Looks good from a quick (and obviously superficial) glance.

**Comment by nathan-russell** [comment]
I actually didn't mean for these changes to get lumped into the existing PR, but hopefully it doesn't turn out to be an issue.

**Comment by eddelbuettel** [comment]
I noticed that too. No big deal --  I think you could have avoided it by starting not only from your fork but with the fork from a distinct branch,

**Comment by thirdwing** [comment]
LGTM. Although this can be in two separate PR.

**Comment by eddelbuettel** [comment]
I don't think it is worth splitting the PRs.  I'll be happy to merge as is.  We don't obsess too much over about squashing all PRs into single commits etc pp.

But of course if someone feels strongly enough about it to make all the changes I won't ignore them...

**Pull request merged**
