### PR TITLE
Rcpp::String and Rcpp::(const_)string_proxy comparison functions

### PR DESCRIPTION
**Pull request by dcdillon**
Pursuant to the discussion on #191, I have added comparison functions (==, !=, <, >, <=, >=) for `Rcpp::String` and `Rcpp::string_proxy` (and `Rcpp::const_string_proxy`).  These have the same semantics as the existing comparisons of `Rcpp::String` to `Rcpp::String`.  There are no changes to existing code, only additions.  The code I used to test is below.  Note that coverage is complete because the `string_proxy (op) String` functions call the comparison functions in the `String` class. 

```c++
// [[Rcpp::export]]
void testComparison(CharacterVector haystack, String needle) {
  for (int i = 0; i < haystack.size(); ++i) {
    Rcpp::Rcout << haystack[i] << " == " << (std::string)needle << " ...";
    if (haystack[i] == needle) {
      Rcpp::Rcout << "true" << std::endl;
    } else {
      Rcpp::Rcout << "false" << std::endl;
    }

    Rcpp::Rcout << haystack[i] << " != " << (std::string)needle << " ...";
    if (haystack[i] != needle) {
      Rcpp::Rcout << "true" << std::endl;
    } else {
      Rcpp::Rcout << "false" << std::endl;
    }

    Rcpp::Rcout << haystack[i] << " > " << (std::string)needle << " ...";
    if (haystack[i] > needle) {
      Rcpp::Rcout << "true" << std::endl;
    } else {
      Rcpp::Rcout << "false" << std::endl;
    }

    Rcpp::Rcout << haystack[i] << " < " << (std::string)needle << " ...";
    if (haystack[i] < needle) {
      Rcpp::Rcout << "true" << std::endl;
    } else {
      Rcpp::Rcout << "false" << std::endl;
    }

    Rcpp::Rcout << haystack[i] << " >= " << (std::string)needle << " ...";
    if (haystack[i] >= needle) {
      Rcpp::Rcout << "true" << std::endl;
    } else {
      Rcpp::Rcout << "false" << std::endl;
    }

    Rcpp::Rcout << haystack[i] << " <= " << (std::string)needle << " ...";
    if (haystack[i] <= needle) {
      Rcpp::Rcout << "true" << std::endl;
    } else {
      Rcpp::Rcout << "false" << std::endl;
    }
  }
}

// [[Rcpp::export]]
void testComparisonConst(const CharacterVector haystack, String needle) {
  for (int i = 0; i < haystack.size(); ++i) {
    Rcpp::Rcout << haystack[i] << " == " << (std::string)needle << " ...";
    if (haystack[i] == needle) {
      Rcpp::Rcout << "true" << std::endl;
    } else {
      Rcpp::Rcout << "false" << std::endl;
    }

    Rcpp::Rcout << haystack[i] << " != " << (std::string)needle << " ...";
    if (haystack[i] != needle) {
      Rcpp::Rcout << "true" << std::endl;
    } else {
      Rcpp::Rcout << "false" << std::endl;
    }

    Rcpp::Rcout << haystack[i] << " > " << (std::string)needle << " ...";
    if (haystack[i] > needle) {
      Rcpp::Rcout << "true" << std::endl;
    } else {
      Rcpp::Rcout << "false" << std::endl;
    }

    Rcpp::Rcout << haystack[i] << " < " << (std::string)needle << " ...";
    if (haystack[i] < needle) {
      Rcpp::Rcout << "true" << std::endl;
    } else {
      Rcpp::Rcout << "false" << std::endl;
    }

    Rcpp::Rcout << haystack[i] << " >= " << (std::string)needle << " ...";
    if (haystack[i] >= needle) {
      Rcpp::Rcout << "true" << std::endl;
    } else {
      Rcpp::Rcout << "false" << std::endl;
    }

    Rcpp::Rcout << haystack[i] << " <= " << (std::string)needle << " ...";
    if (haystack[i] <= needle) {
      Rcpp::Rcout << "true" << std::endl;
    } else {
      Rcpp::Rcout << "false" << std::endl;
    }
  }
}


// R Code
// v <- c("a", "b", "c", "d")
// 
// cat("Non-Const\n")
// testComparison(v, "c")
// cat("\nConst\n")
// testComparisonConst(v, "c")
```

The output of the test code is as follows:

```
Non-Const
a == c ...false
a != c ...true
a > c ...false
a < c ...true
a >= c ...false
a <= c ...true
b == c ...false
b != c ...true
b > c ...false
b < c ...true
b >= c ...false
b <= c ...true
c == c ...true
c != c ...false
c > c ...false
c < c ...false
c >= c ...true
c <= c ...true
d == c ...false
d != c ...true
d > c ...true
d < c ...false
d >= c ...true
d <= c ...false

Const
a == c ...false
a != c ...true
a > c ...false
a < c ...true
a >= c ...false
a <= c ...true
b == c ...false
b != c ...true
b > c ...false
b < c ...true
b >= c ...false
b <= c ...true
c == c ...true
c != c ...false
c > c ...false
c < c ...false
c >= c ...true
c <= c ...true
d == c ...false
d != c ...true
d > c ...true
d < c ...false
d >= c ...true
d <= c ...false
```

### CODE REVIEW

**Comment by thirdwing** [comment]
Thank you for the PR. I have two simple suggestions for you:

(1) do not define `<` or `>`.

The lexicographic in R is different from C++. This has been discussed in #251

 Using your code
```
>testComparison(v, "A")
a == A ...false
a != A ...true
a > A ...true
......
```

But in R
```
> 'a' > 'A'
[1] FALSE
```
(2) please add unit test. There are many examples to follow.

**Comment by kevinushey** [comment]
And unfortunately, the machinery we would like to use from R for string comparison respecting locale + collation [`Scollate`](https://github.com/wch/r-source/blob/5dae3cf0c3686953ebb61ceaa3f8d6166367bad1/src/main/util.c#L2041-L2081) is not exported, so there is no simple way to provide for string comparison on the C++ side that is consistent with R's own comparisons. [dplyr](https://github.com/hadley/dplyr) has had to battle with this a lot over the last release.

Comparing based on `SEXP` location is a rough fallback (since R's global string cache should mean that all distinct strings are stored in separate locations), but this fails for characters which are equal under some locale but have alternate internal representations.

**Comment by dcdillon** [comment]
I've made the changes suggested by @thirdwing.  I think things are good now.

**Comment by eddelbuettel** [comment]
Three cheers for submissions _with_ unit tests...

**Pull request closed without merging**
