### PR TITLE
operator+ for int argument (closes #558)

### LINKED ISSUE #558: Compiling error on OSX using clang++
I met an error when compiling the latest Rcpp on OSX using clang++.

@kevinushey Can you help to confirm this?

A simple file to reproduce the error
```cpp
#include <Rcpp.h>

using namespace Rcpp;

//[[Rcpp::export]]
void test() {
  Datetime d1 = Datetime(946774923.123456);                                                       
  Datetime d2 = d1 + 60*60;
}
```

In R

```
> Rcpp::sourceCpp("test.cpp")
test.cpp:8:20: error: use of overloaded operator '+' is ambiguous (with operand
      types 'Rcpp::Datetime' and 'int')
  Datetime d2 = d1 + 60*60;
                ~~ ^ ~~~~~
/Library/Frameworks/R.framework/Versions/3.2/Resources/library/Rcpp/include/Rcpp/date_datetime/Datetime.h:108:21: note: 
      candidate function
    inline Datetime operator+(const Datetime &datetime, double offset) {
                    ^
test.cpp:8:20: note: built-in candidate operator+(double, int)
  Datetime d2 = d1 + 60*60;
                   ^
test.cpp:8:20: note: built-in candidate operator+(unsigned __int128, int)
test.cpp:8:20: note: built-in candidate operator+(unsigned long long, int)
test.cpp:8:20: note: built-in candidate operator+(unsigned long, int)
test.cpp:8:20: note: built-in candidate operator+(float, int)
test.cpp:8:20: note: built-in candidate operator+(unsigned int, int)
test.cpp:8:20: note: built-in candidate operator+(__int128, int)
test.cpp:8:20: note: built-in candidate operator+(long long, int)
test.cpp:8:20: note: built-in candidate operator+(long, int)
test.cpp:8:20: note: built-in candidate operator+(int, int)
```

### PR DESCRIPTION
**Pull request by eddelbuettel**

### CODE REVIEW

**Comment by thirdwing** [comment]
Passed on OSX with clang++

**Comment by eddelbuettel** [comment]
On Ubuntu I have the usual hard time -- but I have it built under the UBSAN Docker container (using `clang++-3.8`).

Really silly issue under Ubuntu which, once again, has its clang setup borked.  Seems to run some of the unit test C++ files but not all.

**Comment by thirdwing** [comment]
Can I know which image you used? I might have time to look into it.

**Comment by eddelbuettel** [comment]
Failing: any Ubuntu 16.04; fails to link with `-lc++` (as I recall(
Successful: Using [this r-devel-clang-ubsan container](https://hub.docker.com/r/rocker/r-devel-ubsan-clang/) and make sure you use `RD` as the R -- then you get ubsan 'for free' and a working clang.  

We do not have an open ubsan issue, but it bugs me that I cannot build with clang. I used to be able to,

**Comment by kevinushey** [comment]
IIRC, aren't the versions of clang provided by the debian repositories built to use `libstdc++` by default? In other words, attempting to link with `libc++` requires some more work, e.g. versions of clang provided by Homebrew need something like:

```
  CXX="clang++-3.8 -stdlib=libc++"
  CXXFLAGS="$CXXFLAGS -nostdinc++ -I/usr/local/opt/llvm38/lib/llvm-3.8/include/c++/v1"
  LDFLAGS="$LDFLAGS -L/usr/local/opt/llvm38/lib/llvm-3.8/lib"
```

**Comment by eddelbuettel** [comment]
KK, what question are you trying to answer?

I can build (simple) packages just fine via

```
CXX=clang++-3.8 -stdlib=libc++ -I/usr/include/c++/5/ -I/usr/include/x86_64-linux-gnu/c++/5  
CXX1X=clang++-3.8 -stdlib=libc++ -I/usr/include/c++/5/ -I/usr/include/x86_64-linux-gnu/c++/5/     
CC=clang-3.8  
```

But I have an open issue with Rcpp.

**Comment by eddelbuettel** [comment]
And then of course it works on the next attempt.  Hm.

**Comment by eddelbuettel** [comment]
Ah, right, now I remember.  _Building_ works but during `R CMD check` it mysteriously fails:

```
Executing test function test.wrap.unordered.map.string.generic  ... /usr/bin/ld: cannot find -lc++
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [sourceCpp_93.so] Error 1
clang++-3.8 -stdlib=libc++ -I/usr/include/c++/5/ -I/usr/include/x86_64-linux-gnu/c++/5/ -std=c++11 -I/usr/share/R/include -DNDEBUG    -I"/home/edd/git/Rcpp.Rcheck/Rcpp/include" -I"/home/edd/git/Rcpp.Rcheck/Rcpp/u
nitTests/cpp"    -fpic  -O3 -Wall -pipe -Wno-unused -pedantic  -c wrap.cpp -o wrap.o
clang++-3.8 -stdlib=libc++ -I/usr/include/c++/5/ -I/usr/include/x86_64-linux-gnu/c++/5/ -std=c++11 -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -Wl,-z,relro -o sourceCpp_93.so wrap.o -L/usr/lib/R/lib -lR
/usr/share/R/share/make/shlib.mk:6: recipe for target 'sourceCpp_93.so' failed
Error in sourceCpp(file.path(pathToRcppTests, "cpp", file)) : 
  Error 1 occurred building shared library.
```

If anybody has clues, I take'em.  I have given up on this.  No clang for testing for me.

**Comment by kevinushey** [comment]
One possibility -- maybe `-std=c++11` needs to come before `-stdlib=libc++`?

**Comment by eddelbuettel** [comment]
I have some sympathy for that on plain logical ground but then ...  Rcpp is not a C++11 project.

**Comment by kevinushey** [comment]
Yes, but I see that you have `-std=c++11` in your invocation of `clang++-3.8`.

**Comment by eddelbuettel** [comment]
That may be the plugin. My `~/.R/Makevars` is as I quoted it.

**Comment by eddelbuettel** [comment]
Related but different:  I may need `-stdlib=libc++` in the _link_ step not the compilation step.

**Comment by eddelbuettel** [comment]
That is it---if I also set

```
SHLIB_CXXLD=clang++-3.8 -stdlib=libc++
```

it then fails with

```
clang++-3.8 -stdlib=libc++ -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -Wl,-z,relro -o Rcpp.so Date.o Module.o Rcpp_init.o api.o attributes.o barrier.o -L/usr/lib/R/lib -lR
/usr/bin/ld: cannot find -lc++
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

which is (at long last) the same error as the one I get from `R CMD check`.

**Comment by eddelbuettel** [comment]
Ok, I was actually mising the `libc++-dev` package which, once installed, gets me a little further.  But then:

```
edd@max:~/git$ R CMD INSTALL Rcpp_0.12.7.2.tar.gz 
* installing to library ‘/usr/local/lib/R/site-library’
* installing *source* package ‘Rcpp’ ...
** libs
ccache clang++-3.8 -I/usr/include/c++/5/ -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/share/R/include -DNDEBUG -I../inst/include/     -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -O3 -Wall -pipe -Wno-unused -pedantic  -c Date.cpp -o Date.o
ccache clang++-3.8 -I/usr/include/c++/5/ -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/share/R/include -DNDEBUG -I../inst/include/     -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -O3 -Wall -pipe -Wno-unused -pedantic  -c Module.cpp -o Module.o
ccache clang++-3.8 -I/usr/include/c++/5/ -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/share/R/include -DNDEBUG -I../inst/include/     -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -O3 -Wall -pipe -Wno-unused -pedantic  -c Rcpp_init.cpp -o Rcpp_init.o
ccache clang++-3.8 -I/usr/include/c++/5/ -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/share/R/include -DNDEBUG -I../inst/include/     -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -O3 -Wall -pipe -Wno-unused -pedantic  -c api.cpp -o api.o
ccache clang++-3.8 -I/usr/include/c++/5/ -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/share/R/include -DNDEBUG -I../inst/include/     -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -O3 -Wall -pipe -Wno-unused -pedantic  -c attributes.cpp -o attributes.o
ccache clang++-3.8 -I/usr/include/c++/5/ -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/share/R/include -DNDEBUG -I../inst/include/     -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -O3 -Wall -pipe -Wno-unused -pedantic  -c barrier.cpp -o barrier.o
clang++-3.8 -stdlib=libc++ -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -Wl,-z,relro -o Rcpp.so Date.o Module.o Rcpp_init.o api.o attributes.o barrier.o -L/usr/lib/R/lib -lR
installing to /usr/local/lib/R/site-library/Rcpp/libs
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/usr/local/lib/R/site-library/Rcpp/libs/Rcpp.so':
  /usr/local/lib/R/site-library/Rcpp/libs/Rcpp.so: undefined symbol: _ZTISo
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/usr/local/lib/R/site-library/Rcpp’
* restoring previous ‘/usr/local/lib/R/site-library/Rcpp’
edd@max:~/git$ 
```

where


```
edd@max:~/git$ c++filt _ZTISo
typeinfo for std::basic_ostream<char, std::char_traits<char> >
edd@max:~/git$ 
```

Ideas?

**Comment by eddelbuettel** [comment]
In other news:   any comment on this innocent-enough PR?  Good to go in?

**Comment by kevinushey** [comment]
PR LGTM.

**Comment by eddelbuettel** [comment]
Ok, that makes it two LGTM so I'll fold this one in.

**Pull request merged**
