### PR TITLE
Enhance is check for module object

### PR DESCRIPTION
**Pull request by tqchen**
fix to #380

### CODE REVIEW

**Comment by eddelbuettel** [comment]
That probably requires a reverse-dependency check but I am traveling right now and may not get to it for some time.

**Comment by tqchen** [comment]
please take your time. we have applied a local specialization path to our package for now. Thanks

**Comment by thirdwing** [comment]
BTW, maybe you can add a simple test in https://github.com/RcppCore/Rcpp/tree/master/inst/unitTests/testRcppModule/src

**Comment by eddelbuettel** [comment]
+1 for adding unit test support to this (or any, really) pull request.

**Comment by kevinushey** [comment]
This does not seem like the right change. I think the only reason you're getting punted into the module method is because you haven't let Rcpp understand how to handle `as` / `wrap`.

Please read https://cran.r-project.org/web/packages/Rcpp/vignettes/Rcpp-extending.pdf for more information on how you can let `Rcpp::as<T>` and `Rcpp::wrap` understand how to interact with custom classes; I am guessing your problem will go away if you do this.

**Comment by thirdwing** [comment]
A very simple example to make things clear. Just use our `RcppModuleWorld`.

`check_module` is nothing but `Rcpp::is<RcppModuleWorld>(x)`.

```
> m <- new(RcppModuleWorld)
> m
C++ object <0x2858180> of class 'RcppModuleWorld' <0x306a480>
> check_module(m)
[1] TRUE
> check_module(1)
Error: expecting an external pointer
```

If other things pass into this function, we will get a warning, since `env.get(".cppclass")` return a `NULL`.

@tqchen thought we need to check whether it is `NULL`. If it is `NULL`, we should return `FALSE`, not a warning.

**Comment by tqchen** [comment]
I think @thirdwing explains my point. Ideally it would be great ```Rcpp::is<RcppModuleWorld>```   only return true or false. So we can use it to check parameters. 

For example, we can use this to check if input parameter is a certain type, and give more friendly error message to the user.

```c++
void dosomething(Rcpp::List param_list) {
  for (size_t i = 0; i < param_list.size(); ++i) {
    if (!Rcpp::is<RcppModuleClassA>(param_list[i]))
        throw Rcpp::exception("The input parameter is expected to be list of RcppModuleClassA")
  }
}
```

**Comment by kevinushey** [comment]
Thanks, it indeed looks like the `RCPP_EXPOSED_CLASS` is responsible for exposing `as` / `wrap` methods, hence where the dispatch is coming from. The PR looks fine to me, then.

**Comment by eddelbuettel** [comment]
Agreed -- will merge now and launch a full reverse-dependency test.  We can always revert should something bubble up (which we have no reason to expect).

**Pull request merged**
