### PR TITLE
Update XPtr.h

### PR DESCRIPTION
**Pull request by thk686**
Added "tag" method to retrieve the tag value.

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Please open an issue motivating the required change, preferably with an example.

Please add a unit test.

[ Optional ] Please add an entry to ChangeLog, or to minimise overlap between branches suggest one here. Ditto for NEWS.Rd.

**Comment by eddelbuettel** [comment]
All this is explained on [Contributing.md](https://github.com/RcppCore/Rcpp/blob/master/Contributing.md)  which clearly nobody bothers to read.

Also, we tend to prefer pull request that at least compile.

**Comment by thk686** [comment]
On Sat, Dec 2, 2017 at 5:29 PM, Dirk Eddelbuettel <notifications@github.com>
wrote:

> All this is explained on Contributing.md
> <https://github.com/RcppCore/Rcpp/blob/master/Contributing.md> which
> clearly nobody bothers to read.
>
> Also, we tend to prefer pull request that at least compile.
>

That seems pretty sensible. :-)

THK

**Comment by eddelbuettel** [comment]
Closing this for lack of follow-up, on top of missing prior coordination / motivation.

**Pull request closed without merging**
