### PR TITLE
Alternative syntax for creating vectors and matrices without initializin...

### PR DESCRIPTION
**Pull request by romainfrancois**
Alternative syntax for creating vectors and matrices without initializin..., e.g.

```
// create a numeric vector of size 5 without initializing the values
// similar to NumericVector x = no_init(5) ;
NumericVector x(5, _) ;

// not initializd matrix
// no equivalent with no_init
// similar to IntegerMatrix m = Rf_allocMatrix( INTSXP, 6, 9 ) ;
IntegerMatrix m(6,9,_) ;
```

### CODE REVIEW

**Comment by romainfrancois** [comment]
The proposed syntax did not compile before, so it only adds a feature, it does not change anything elsewhere.

**Comment by jjallaire** [comment]
What about adding an init flag to the existing size based constructors instead? e.g.

```cpp
Vector( const int& size, bool init = true)
```

**Comment by eddelbuettel** [comment]
I think prefer JJ's proposal with a `bool` that defaults to `true`. I still favor defensive programming, and we initialized before -- so you changing that ought to require an explicit toggle.

**Comment by romainfrancois** [comment]
Well `Vector(int, bool)` currently has a meaning, e.g. `NumericVector(3, true)` would make `c(1,1,1)` so what @jjallaire suggests would change behaviour. I see no way that this is any acceptable, especially given your usual set of arguments. 

What I'm suggesting adds an overload that was not previously taken, that did not compile before and that visually is, at least to me appealing thanks to the `_`. 

@eddelbuettel I'm not proposing to change any behaviour that already exist. Just adding something, something new. 

It makes even more sense for matrices where there is currently no way to express "no initialization".  

But whatever, I'm not going to argue much more, if you don't want this, please close this PR.

**Comment by jjallaire** [comment]
Okay, I didn't realize that the bool would conflict.

I'm good with this change but want to drill into one thing: it didn't
compile before because of something about the type or due to compiler
idiosyncrasies? (just want to make sure we don't put in anything that blows
up on older compilers like gcc 4.2, on Solaris, etc.).

**Comment by eddelbuettel** [comment]
Also overlooked the existing `Vector(int, bool)`.  Need to think about this some more. 

(We also have two other PRs to review from the GSoC pipeline...)

**Comment by eddelbuettel** [comment]
May I petition for a variant that does not use `internal::NamedPlaceHolder` but rather something explicit?   

E.g. could it use a variant of `Rcpp::$OBJECT::create`, ie `Rcpp::NumericVector::noinit(dim arguments)` ?

**Comment by kevinushey** [comment]
Any reason why this is preferred over e.g. `NumericMatrix foo = no_init(10, 10)`?

I agree having a mechanism for generating non-initialized objects is useful; just not sure if this is the best way to do it.

**Comment by eddelbuettel** [comment]
Or, if I may,  `NumericMatrix foo = noInit(10, 10)` ?

**Comment by kevinushey** [comment]
@eddelbuettel, my point was we already have `no_init` for matrices; it was added a little while back. Ie, this works:

```
#include <Rcpp.h>
using namespace Rcpp;

// [[Rcpp::export]]
NumericMatrix test() {
    NumericMatrix mat = no_init(10, 10);
    return mat;
}
```

**Comment by eddelbuettel** [comment]
@kevinushey Point taken.

And as it works for vectors too (see below), do we need the PR?

```{.r}
R> cppFunction('NumericVector foo(int n) { NumericVector v = no_init(n); return v; }')
R> foo(3)
[1] 1.71608e-316 1.71608e-316 1.71608e-316
R> 
```

**Comment by romainfrancois** [comment]
Alright. I guess I'm the only one to see the aesthetics of the solution using `_`. Closed.

**Comment by romainfrancois** [comment]
@jjallaire it did not compile before because `_` does not convert to whatever the underlying type of the vector is, so this would have been safe across compilers, etc ... 

Anyway, always nice to have reminders about why I'm not in this project anymore.

**Pull request closed without merging**
