### PR TITLE
use documented R API function for extptr addr

### PR DESCRIPTION
**Pull request by kevinushey**
Closes https://github.com/RcppCore/Rcpp/issues/1097.

"In theory" this PR should be safe ... but I'd definitely understand if we still don't want to take it so close to release.

#### Checklist

- [x] Code compiles correctly
- [x] `R CMD check` still passes all tests
- [ ] Prefereably, new tests were added which fail without the change
- [x] Document the changes by file in [ChangeLog](https://github.com/RcppCore/Rcpp/blob/master/ChangeLog)

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Thanks, on balance I think this will have to wait til after 1.5.0 is out.

**Comment by eddelbuettel** [comment]
I rebased this against `master` which has the 1.0.5 release now on CRAN, and will add a new minor release version 1.0.5.1 for it.

Ok with you I hope?  ;-)

**Comment by kevinushey** [comment]
LGTM -- thanks!

**Comment by eddelbuettel** [comment]
I was a little slow preparing a new rev.dep check for this 1.0.5.1 rc, but it is running. I may give a few hours, or maybe even wait til tomorrow, to see all is ok as expected and then merge.

**Comment by eddelbuettel** [comment]
It's over 1/3 done and looking reasonable so far, so merging this now.

**Comment by eddelbuettel** [comment]
Just for completeness: no issue came up, the reverse depends check concluded just fine, and I just commited the summary to the usual `rcpp-logs` repo.

**Pull request merged**
