### PR TITLE
change hashing function to return unsigned int

### PR DESCRIPTION
**Pull request by thirdwing**

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Looks good to me!

**Comment by eddelbuettel** [comment]
Any other thumbs up besides my overused one?

**Comment by coatless** [comment]
Change context:

`int` => `unsigned int` since the [hashing macro is defined to return `unsigned int`](https://github.com/RcppCore/Rcpp/blob/4e14955443544d2a4db9c58becbadd915ee463ae/inst/include/Rcpp/hash/IndexHash.h#L45-L47)

**Comment by coatless** [comment]
Looks like one of the variables missed a change over:

https://github.com/thirdwing/Rcpp/blob/a7cda55f975bd0c0313faefeb9ade0e7cf27a4e9/inst/include/Rcpp/hash/IndexHash.h#L170

**Comment by eddelbuettel** [comment]
Yes, also see the now closed (because too "jumbo") PR #556

**Comment by thirdwing** [comment]
I have updated the code.

**Comment by eddelbuettel** [comment]
In it goes!

**Pull request merged**
