### PR TITLE
fix wrong return type in product of dimensions

### PR DESCRIPTION
**Pull request by fplaza**
Sorry guys...
I should have tested it first.

### CODE REVIEW

**Comment by thirdwing** [comment]
It doesn't matter. 

Very few people are using that large vector or matrix. It will be appreciated it you can test more.

**Comment by fplaza** [comment]
I am working on an R package which processes very large matrices.
Everything works fine with this patch.

**Comment by thirdwing** [comment]
@eddelbuettel Can you look at this?

**Comment by eddelbuettel** [comment]
@thirdwing I sort-of had.  I think it is good as is.

**Comment by kevinushey** [comment]
Looks good to me.

**Pull request merged**
