### PR TITLE
Add rng parameter to Rcpp::export to prevent inclusion of RNGScope in generated code

### PR DESCRIPTION
**Pull request by jjallaire**

### CODE REVIEW

**Comment by eddelbuettel** [comment]
I like it !  What was the motivation today?  Leakage?  Saving a cycle here or there?  Drew's post?

One suggestion: a _positive_ term ("rng") for a _negative_ action ("do _not_ include") is weird.  Would it make sense to call it `norng` instead of `rng`?

**Comment by kevinushey** [comment]
It seems like we default to `rng = TRUE` but someone could write:

    // [[Rcpp::export(rng = FALSE)]]

if so desired. Is that correct @jjallaire?

**Comment by jjallaire** [comment]
I knew this had been asked for a few times and it's hung over my head that we didn't support it. I figured as long as I am mucking around in the attributes code I might as well just do it :-)

Kevin is correct, the default is rng = true so the only meaningful value is rng = false (which doesn't have the inversion of meaning problem you described)

**Comment by jjallaire** [comment]
Do you think I should also support TRUE and FALSE (I currently only support true and false lowercase)

**Comment by kevinushey** [comment]
I would say yes (I almost reflexively wrote `FALSE` just because I was thinking in `R` mode; also R provides `TRUE` and `FALSE` defines anyway so users might be accustomed to using that already.)

**Comment by jjallaire** [comment]
Okay, I'll update to support TRUE and FALSE as well.

**Pull request merged**
