### PR TITLE
Pr/1183

### PR DESCRIPTION
**Pull request by traversc**
I added some syntax checking based on @Enchufa2 's feedback.

Tests here: https://github.com/traversc/RcppTest/tree/master/inst. These tests incorporate the examples from @Enchufa2. 

Currently, you can run them with `make install && make test`, but I'm not sure the best way to add the tests as a pull request.

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Me too, of course. Alwats happy to help with `tinytest` which, via its "it is just a script" approach really makes it easy.

**Comment by Enchufa2** [comment]
@traversc Checking your `RcppTest` repo, I see that you made a package specifically to test this. So the idea would be to integrate those tests into [`inst/tinytest`](https://github.com/RcppCore/Rcpp/tree/master/inst/tinytest) as part of this PR, removing the manual `print`s, `stopifnot`s, etc., and replacing them with the proper `tinytest` utilities that `Rcpp` already uses. You can take a look there to see how other similar tests are implemented.

**Comment by Enchufa2** [comment]
Looking very good, thanks for all the changes! I left a few more comments. I also activated the CI and everything passes (don't worry about the covr report).

> @Enchufa2 Replies inline. A bunch of commits for minor things, but hopefully they can be squashed at the end.

Sure, no problem.

> Also, one comment: I noticed the ChangeLog is a mixture of spaces and tabs -- is that intentional?

Yeap, I asked the same thing some time ago, but I don't recall @eddelbuettel's answer. :)

**Comment by traversc** [comment]
Updated, hopefully I addressed everything properly this time :)

**Comment by eddelbuettel** [comment]
Yep that's the idea: by squashing it into our pr/1183 branch the pending PR #1184 should auto-update.

Giving that a whirl now.

**Pull request merged**
