### PR TITLE
Enable e.g. 'a[b > 3] = b[b > 3]'

### PR DESCRIPTION
**Pull request by thirdwing**
This for #345 .

It is just a combination of code from @kevinushey and @fabian-s .

I think converting to `Vector` is better than defining `length()` and `get()` for `SubsetProxy`.

### CODE REVIEW

**Comment by kevinushey** [comment]
Thanks!

What happens when we attempt to assign non-conforming types, e.g. if `x` is a `NumericVector` and `y` is an `IntegerVector`? We should have test cases that ensure these throw or convert properly (seems like it could be hairy)

**Comment by thirdwing** [comment]
```
#include <Rcpp.h>
using namespace Rcpp;

// [[Rcpp::export]]
IntegerVector subset_assign_subset(NumericVector x) {
    IntegerVector y(x.size());
    y[x > 3] = x[x > 3];
    return y;
}

/*

> Rcpp::sourceCpp("test.cpp")
> subset_assign_subset(1:6)
[1] 0 0 0 4 5 6
> x <- c(1.2, 2.3, 3.4, 4.5)
> subset_assign_subset(x)
[1] 0 0 3 4

*/
```

**Comment by kevinushey** [comment]
It looks like type coercion is already properly handled so I think this is good to go. E.g. this gives a compiler error, as hoped:

```
#include <Rcpp.h>
using namespace Rcpp;

// [[Rcpp::export]]
IntegerVector subset_assign_subset(CharacterVector x) {
  IntegerVector y(x.size());
  y[x > 3] = x[x > 3];
  return y;
}
```

**Comment by eddelbuettel** [comment]
Having a few unit tests would be nice.

**Comment by eddelbuettel** [comment]
Appreciate the extra tests!   Merging now.

**Pull request merged**
