### PR TITLE
Fix #278 by automatically inserting whitespace

### LINKED ISSUE #278: Error when passing arguments by reference
I got compilation errors when I compiled the following code using `Rcpp::sourceCpp`.
```c++
#include <Rcpp.h>
using namespace Rcpp;

// [[Rcpp::export]]
NumericMatrix test(const NumericMatrix &data){
  return data;
}
```

The error messages said,
> error: invalid initialization of non-const reference of type ‘Rcpp::ConstInputParameter<Rcpp::Matrix<14, Rcpp::PreserveStorage> >&’ from a temporary of type ‘SEXPREC**’
> error: invalid conversion from ‘Rcpp::ConstInputParameter<Rcpp::Matrix<14, Rcpp::PreserveStorage> >*’ to ‘int’
> error:   initializing argument 1 of ‘Rcpp::Matrix<RTYPE, StoragePolicy>::Matrix(const int&) [with int RTYPE = 14, StoragePolicy = Rcpp::PreserveStorage]’

Then, I checked `RcppExports.cpp` generated by `Rcpp::compileAttributes`, which was like as follows.
```c++
// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// test
NumericMatrix test(const NumericMatrix &data);
RcppExport SEXP test_pkg_test(SEXP &dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const NumericMatrix >::type &data(&dataSEXP);
    __result = Rcpp::wrap(test(&data));
    return __result;
END_RCPP
}
```

------

It seems that the above code
```c++
   Rcpp::traits::input_parameter< const NumericMatrix >::type &data(&dataSEXP);
    __result = Rcpp::wrap(test(&data));
```
should be
```c++
    Rcpp::traits::input_parameter< const NumericMatrix &>::type data(dataSEXP);
    __result = Rcpp::wrap(test(data));
```

This problem did not occur in Rcpp(0.11.3)
Here is the information about my environment
- centos6.5
- gcc 4.4.7
- R 3.1.0
- Rcpp 0.11.5.1

Thank you.

### PR DESCRIPTION
**Pull request by kafku**
fix #278 just by simply converting `&foo` into `& foo`.

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Thanks, we'll take a look.  This is fairly deep in @jjallaire 's territory, and he may not get to it on the weekend.

**Comment by jjallaire** [comment]
I'm going to need to take some time to carefully examine whether this has
the potential to break anything. Don't have time for that right now but
should within the next couple of weeks (also not a great time to take a PR
as we are just about to roll a release).

On Sat, Nov 14, 2015 at 1:14 PM, Dirk Eddelbuettel <notifications@github.com

**Comment by eddelbuettel** [comment]
Actually, the 0.12.2 release is finalized and has been sitting in the incoming queue in Vienna since yesterday morning (when I just seem to have missed a batch of processing).  I would expect it to be on CRAN within a day.

**Comment by jjallaire** [comment]
Thanks @kafku. Could you send another PR with appropriate ChangeLog and NEWS entries?

**Comment by eddelbuettel** [comment]
Or I'll just do it as I often do...

**Comment by kafku** [comment]
Unfortunately, The Japanese, including me, cannot write appropriate English.

**Comment by eddelbuettel** [comment]
I am on it :)   Typing as I commute.

**Comment by kafku** [comment]
@eddelbuettel  
I appreciate it.

**Pull request merged**
