### PR TITLE
allow the syntax Matrix mat(no_init(n,nc))

### PR DESCRIPTION
**Pull request by romainfrancois**
see https://github.com/tidyverse/dplyr/pull/3841#issuecomment-422828179 for the back story.

### CODE REVIEW

**Comment by krlmlr** [comment]
Are the test failures related to this PR? See https://github.com/RcppCore/Rcpp/pull/904/files?utf8=%E2%9C%93&diff=split&w=1 to hide the whitespace-only changes. `ChangeLog` has a conflict too.

**Comment by romainfrancois** [comment]
There might be a typo in the runit file <grimacing>

**Comment by eddelbuettel** [comment]
Indeed:

    m <- runit_no_init_matrix_cotr()

That wanted to be `...ctor()`

Trying to test before pushing is sometimes a good idea, as is opening an issue and discussing before throwing a PR over the fence without context.

**Comment by eddelbuettel** [comment]
I'll clean this up.  Next time, please 

1.  File an issue first.  Establish consensus what changes be made.
2.  Send a PR.  Ideally test it.  Even more ideally, test reverse dependencies.

Thanks.

**Comment by romainfrancois** [comment]
I open an issue when i am onto something, and it does not appear trivial to do the work immediately. For example with the Rcpp::init the other day. 

Otherwise pull request are typically a much better format as they offer a way to discuss and bind additional context. 

I did some testing, but then my time is a limited resource too so i tend to trust travis for the rest. 

As for reverse dependency tests, i’m clearly not going to do it to test something that previously failed to compile before the changes.

**Comment by eddelbuettel** [comment]
This repo and project operate with a set of suggested rules which have worked well for us in the past.  Issue tickets first is one of those, and we would appreciate it if you could play along just like ever other repeat contributor does.

So for this, please cherry-pick in this commit of mine into your branch and hence this PR: https://github.com/RcppCore/Rcpp/commit/c9da8031ed303abaf51493e6c0231bf29761ae8a

**Comment by romainfrancois** [comment]
Sure will do.

**Comment by eddelbuettel** [comment]
> Sure will do.

When were you planning to do that?

**Comment by romainfrancois** [comment]
I meant "I will follow the rules".

**Comment by eddelbuettel** [comment]
Can you please do 

> So for this, please cherry-pick in this commit of mine into your branch and hence this PR: c9da803

or do prefer that I close this and create a new PR?

**Comment by romainfrancois** [comment]
I won't have time to do anything until next week. Please do whatever you think is best.

**Comment by eddelbuettel** [comment]
Helpful.  That takes 2 seconds.

**Pull request closed without merging**
