### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by robertzk**

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Thanks, @robertzk.  

Now that you are a "formal Rcpp contributor" and also hang in Chi-town, can I buy you a beer one of these days?  Will you be at Jak's for the RUG with plot.ly tomorrow?

**Comment by robertzk** [comment]
Certainly! I'll seek you out before/after the talk tomorrow.

P.S. I promise more substantive open-source contributions next time...

**Comment by eddelbuettel** [comment]
:+1:   -- I'll come from work so after the talk may work better.  And now we're "hedged" -- if the talk were to be terrible we can go straight to drinking ;-)

**Comment by robertzk** [comment]
Are you around now? @eddelbuettel

**Pull request merged**
