### PR TITLE
Feature/print function

### PR DESCRIPTION
**Pull request by eddelbuettel**
This adds a new function print() as a wrapper for Rf_PrintValue

### CODE REVIEW

**Comment by jjallaire** [comment]
One question: why not make this an inline function and dispense with registration/routines bits?

**Comment by eddelbuettel** [comment]
That is what I did initially. 

I have no strong feeling either way.

**Comment by jjallaire** [comment]
Got it. My bias is to keep as much inline as possible to minimize the probability of version mishmash issues. That said, if someone is using this function they clearly depend on Rcpp 0.11.5 and so the results of running against 0.11.4 are at best undefined. Also agree that having a simple worked example is valuable.

**Comment by eddelbuettel** [comment]
Yeppers -- agree on all counts.

**Pull request merged**
