### PR TITLE
Allow use of attributes without Rcpp:: prefix when preceded by 'using namespace Rcpp'

### PR DESCRIPTION
**Pull request by jjallaire**
Note that this PR is branched off the previous rng = false one so should only be taken after that one is.

### CODE REVIEW

**Comment by jjallaire** [comment]
I'm actually not sure about this PR. In reviewing the C++11 specification on attributes it's my understanding that attribute namespaces have nothing to do with C++ namespaces and are just a convention to prevent various attribute schemes from stomping on each other. 

This PR actually attempts to detect "using namespace Rcpp" and use that to determine if non-namespaced attributes are supported. This seems incorrect from the standpoint of emulating "real" attributes.

Since the comment-based attributes are our own scheme we could certainly feel free to not require the Rcpp:: prefix, but if we do I think it should be unconditional and have nothing to do with "using namespace Rcpp". 

What does everyone think about not requiring the "Rcpp::" prefix? I could see it both ways and will go with whatever the consensus is.

**Comment by eddelbuettel** [comment]
I am not a huge fan.  The cost of prefixing via `Rcpp::` is very small, and I find it has a clear benefit of adding clarity.

**Comment by jjallaire** [comment]
Okay, I think I agree. I'll close this for now.

**Comment by eddelbuettel** [comment]
Thank you!  I wasn't going to fight it -- majority vote has its merits.  And we can revisit.

**Pull request closed without merging**
