### PR TITLE
remove many usages of 'Rf_eval' (#498)

### PR DESCRIPTION
**Pull request by kevinushey**
As `Rf_eval` may blow up in our face on Windows.

### CODE REVIEW

**Comment by kevinushey** [comment]
No idea what the Travis error is yet:

```
Error executing .setUp before test.wrap.unordered.map.string.int : Error in eval(substitute(expr), envir, enclos) : 
  object 'datafile' not found
```

**Comment by eddelbuettel** [comment]
@kevinushey What shall we do with this one?  As I recall the underlying issue was actually due to the toolchain as opposed to the code, so maybe time to close this?

**Comment by kevinushey** [comment]
Yes, I think we can close this although I think at least some of the existing usages of `Rf_eval` are code smells,

**Comment by eddelbuettel** [comment]
Shall we retreat for that and start smaller?  I am a little worried that this changeset mostly failed...

**Comment by kevinushey** [comment]
Sounds good.

**Pull request closed without merging**
