### PR TITLE
Allow new_env() to create an environment with a specified parent

### PR DESCRIPTION
**Pull request by lionel-**
Hello,

This is a small change to have a more useful way of creating environments with Rcpp.

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Thanks for the contribution.  Do you have a usage example?   And/or test case we can add to the unit tests?

**Comment by lionel-** [comment]
For example you can capture the calling environment to your cpp function from its R wrapper with `parent.frame()`. Then you create a new environment (call it `my_env`) that has the calling env as parent. You can put several things in there, knowing that it won't have side effects, and then evaluate some R code with `Rf_eval()` in this environment. Variable lookup will first take place in `my_env`, then in the calling env, then its parent and so on.

I could add a test that checks that the parent is the correct one if you want.

**Comment by lionel-** [comment]
Here you go.

**Comment by lionel-** [comment]
wait a minute, I made a mistake in there

why did the test not fail? :/

**Comment by lionel-** [comment]
ok, I should have used `checkIdentical()`

should be good now

**Comment by eddelbuettel** [comment]
Looks good.  Odd indeed that `checkEquals()` failed there.

**Comment by lionel-** [comment]
Thanks for your quick review!

**Pull request merged**
