### PR TITLE
drop support for user-defined databases

### PR DESCRIPTION
**Pull request by kevinushey**
### Pull Request Template for Rcpp

Closes https://github.com/RcppCore/Rcpp/issues/1313.

#### Checklist

- [x] Code compiles correctly
- [x] `R CMD check` still passes all tests
- [ ] Preferably, new tests were added which fail without the change
- [x] Document the changes by file in [ChangeLog](https://github.com/RcppCore/Rcpp/blob/master/ChangeLog)

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Nice catch in #1313. I don't even recall what those user-define dbs were....

**Comment by eddelbuettel** [comment]
I am kinda minutes/hours/days from a new release so how would you feel if I delayed this til after the release. Given that @mattfidler saw this I would think we need a full rev.dep check (as we change the API surface) which I would rather avoid now.  Thoughts?

**Comment by kevinushey** [comment]
For sure, definitely no rush on this (or the other PR I just put up).

**Comment by mattfidler** [comment]
For me I worked around it ao of CRAN does ask for an update I am ready.

I dont mind waiting either.

**Comment by eddelbuettel** [comment]
Reverse dependency check is now 50% done, no new regressions yet.

**Comment by eddelbuettel** [comment]
The reverse depends run had no new issues, so merging this now.  Had to do a micro-commit over conflicts in ChangeLog, will do one more clean-up (fixing tabs/spaces etc) once merged and once I increment the micro release.

**Pull request merged**
