### PR TITLE
comment-out R::pythag

### PR DESCRIPTION
**Pull request by eddelbuettel**
Per email from BDR

### CODE REVIEW

**Comment by eddelbuettel** [comment]
No comments by anyone?  Should be harmless -- may just merge in a few ...

**Comment by kevinushey** [comment]
We might (?) need a few more changes on our side:

```
inst/include/Rcpp/sugar/functions/complex.h
28:# define RCPP_HYPOT ::Rf_pythag

inst/include/Rcpp/sugar/undoRmath.h
110:#undef pythag

inst/include/Rcpp/Rmath.h
222:    inline double pythag(double a, double b)        { return ::Rf_pythag(a, b); }
```

I think the bit in `undoRmath.h` can stay, but we might want to tweak what we have in `complex.h`:

```
kevin@cdrv:~/r/pkg/Rcpp [rng-state]
$ ag -Q "RCPP_HYPOT"
inst/include/Rcpp/sugar/functions/complex.h
26:# define RCPP_HYPOT ::hypot
28:# define RCPP_HYPOT ::Rf_pythag
83:             y.r = ::log( RCPP_HYPOT( x.r, x.i ) );
90:         if( (mag = RCPP_HYPOT(z.r, z.i)) == 0.0)
144:    t1 = 0.5 * RCPP_HYPOT(x + 1, y);
145:    t2 = 0.5 * RCPP_HYPOT(x - 1, y);
```

If I understand correctly, R removed that function because C99 now defines `::hypot()` and so R doesn't need to provide its own definition. (If I understand correctly, `Rf_pythag()` was R's own definition of `::hypot()`, for platforms that didn't provide it back in the day)

**Comment by kevinushey** [comment]
That said, if everything compiles and checks okay we can probably leave it as is?

**Comment by eddelbuettel** [comment]
There is indeed a bit more.  You first catch is good:  RCPP_HYPOT is conditionally defined with a now-dead fallback.  The `undef` is harmless.  The `inline` we can just comment out as well.

The use of `RCPP_HYPOT` may need a second look as RCPP_HYPOT now has no fallback. Question is then ... would `#ifdef HAVE_HYPOT` ever not be true?  And if so, shall we just emit a warning there?

`man 3 hypot` points to C99, POSIX.1-2001, POSIX.1-2008.  Good enough?

Also:

```sh
edd@rob:~$ grep HAVE_HYPOT ~/svn/r-devel/config.status 
S["RMATH_HAVE_HYPOT"]="# define HAVE_HYPOT 1"
D["HAVE_HYPOT"]=" 1"
edd@rob:~$ 
```

**Comment by eddelbuettel** [comment]
The cleanest may just be to rewrite `complex.h` and do away with `RCPP_HYPOT` in favour of `::hypot`. Let me pile that on later today.

**Comment by kevinushey** [comment]
I think `HAVE_HYPOT` is effectively always true since (as you pointed out) it's defined by the C99 standard and I think R requires C99 or greater during compilation of R + extensions.

**Comment by eddelbuettel** [comment]
@kevinushey That was an excellent catch.  I maded some changes, when you have moment, could you peruse?

**Comment by kevinushey** [comment]
LGTM -- thanks for taking care of this!

**Pull request merged**
